use phonepe;
select distinct quater from agg_transaction ;
select distinct year from agg_transaction;
select sum(transacion_amount)as Transacion_amount,state,year,quater from agg_transaction where year='2024' and quater='2' group by state order by Transacion_amount desc;
select sum(RegisteredUsers) as RegisteredUsers,state,year,quater from agg_user where year = '2024' and quater='2' group by state order by RegisteredUsers desc;
select sum(Transacion_amount) as Transaction_amount,sum(Transacion_count) as Transaction_Count,State,Year from agg_transaction group by state,Year  order by Transaction_amount,Transaction_count desc;
select distinct transacion_type from agg_transaction;
select sum(transacion_count) as Transaction_Count,transacion_type as Transaction_Type from agg_transaction group by Transaction_Type order by Transaction_Count desc;
select sum(Transacion_amount) as Transaction_Amount,transacion_type as Transaction_Type from agg_transaction group by Transacion_type order by Transaction_Amount desc;
select distinct state from agg_transaction;
select sum(Transacion_amount) as Transaction_Amount,transacion_type as Transaction_Type,state from agg_transaction where state= "tamil-nadu" group by Transaction_Type order by Transaction_Amount desc;
select sum(Transacion_amount) as Transaction_Amount,quater,year,state from agg_transaction where year='2018' group by year,quater order by Transaction_amount desc;
select sum(RegisteredUsers) as RegisteredUsers,state,year,quater from agg_user where year = '2018' and quater= '2' group by state order by RegisteredUsers desc;
select sum(RegisteredUsers) as RegisteredUsers,quater from agg_user group by quater order by RegisteredUsers desc;
select sum(RegisteredUsers) as RegisteredUsers,state,quater from agg_user where state="maharashtra" group by state,quater order by RegisteredUsers desc;
select sum(RegisteredUsers) as RegisteredUsers,quater as Quarter,year from agg_user where year = '2018' group by year,quater order by RegisteredUsers desc;
select  sum(RegisteredUsers) as RegisteredUsers, state from agg_user where year = '2018' group by state order by RegisteredUsers desc limit 20;
select district_name, sum(Transacion_amount) as Transaction_Amount FROM top_transaction where district_name is not null AND district_name != 'none' group by district_name order by transaction_amount desc limit 10;
select state,sum(Transacion_amount) as Transaction_Amount FROM top_transaction group by state order by transaction_amount desc limit 10;
select pincodes, sum(Transacion_amount) as Transaction_Amount FROM top_transaction where pincodes is not null AND pincodes != 'none' group by pincodes order by transaction_amount desc limit 10;
select state,sum(Transacion_amount) as Transaction_Amount FROM top_transaction group by state order by transaction_amount asc limit 10;
select district_name, sum(Transacion_amount) as Transaction_Amount FROM top_transaction where district_name is not null AND district_name != 'none' group by district_name order by transaction_amount asc limit 10;
select district_name, sum(Transacion_amount) as Transaction_Amount,state FROM top_transaction where state='tamil-nadu'and district_name is not null AND district_name != 'none' group by district_name,state order by transaction_amount desc;
select state,sum(RegisteredUsers) as RegisteredUsers FROM top_user group by state order by RegisteredUsers desc limit 10;
select District_Name , sum(RegisteredUsers) as RegisteredUsers FROM top_user where District_Name is not null AND District_Name != 'none' group by District_Name order by RegisteredUsers desc limit 10;
select pincodes,sum(RegisteredUsers) as RegisteredUsers FROM top_user where pincodes is not null AND pincodes != 'none' group by pincodes order by RegisteredUsers desc limit 10;
select state,sum(RegisteredUsers) as RegisteredUsers FROM top_user group by state order by RegisteredUsers asc limit 10;
select District_Name ,sum(RegisteredUsers) as RegisteredUsers FROM top_user where District_Name is not null AND District_Name != 'none' group by District_Name order by RegisteredUsers asc limit 10;
select sum(RegisteredUsers) as RegisteredUsers ,quater as Quarter from top_user where year ='2024' group by quater order by RegisteredUsers desc;
select state,sum(Transacion_count) as Transaction_Count FROM top_transaction group by state order by Transaction_Count desc ;
select state,sum(Transacion_amount) as Transaction_Amount FROM top_transaction group by state order by transaction_amount desc limit 10;
select state,sum(Transacion_amount) as Transaction_Amount FROM top_Insurance group by state order by transaction_amount desc limit 10;
select District_Name , sum(Transacion_amount) as Transaction_Amount FROM top_Insurance where District_Name is not null AND District_Name != 'none' group by District_Name order by transaction_amount desc limit 10;
select pincodes, sum(Transacion_amount) as Transaction_Amount FROM top_insurance where pincodes is not null AND pincodes != 'none' group by pincodes order by transaction_amount desc limit 10;
select state,sum(Transacion_amount) as Transaction_Amount FROM top_insurance group by state order by transaction_amount asc limit 10;
select District_Name ,sum(Transacion_amount) as Transaction_Amount FROM top_insurance where District_Name is not null AND District_Name != 'none' group by District_Name order by transaction_amount asc limit 10;
select state,sum(Transacion_count) as Transaction_Count FROM top_insurance group by state order by Transaction_Count desc ;
select district_name, sum(Transacion_amount) as Transaction_Amount,state FROM top_insurance where state = 'tamil-nadu' and district_name is not null AND district_name != 'none' group by district_name,state order by transaction_amount desc;
select sum(Transacion_count) as Transaction_Count,sum(Transacion_amount) as Transaction_Amount ,state from top_insurance where year='2024' group by state order by Transaction_Amount desc,Transaction_Count desc;
select sum(Transacion_count) as Transaction_Count,sum(Transacion_amount) as Transaction_Amount ,state from top_transaction where year= '2024' group by state order by Transaction_Amount desc ,Transaction_Count desc;

    
